name: ugId
description: A Dapp for Digital Identity Profile.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.5.0
  flutter_easyloading: ^2.2.1
  http: ^0.12.0+2
  qr_flutter: ^3.2.0
  flutter_spinkit: ^4.1.1
  qr_code_scanner: ^0.0.13
  web3dart: ^1.2.3
  ethereum: ^4.0.2
  velocity_x: ^1.0.1
  web_socket_channel: ^1.1.0
  provider: ^4.3.2+3
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NovaMono
      fonts:
        - asset: fonts/NovaMono-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
  #